name: Sarath's website

tagline: Sarath's personal website, blog and portfolio.

description: >-  
  CyberShark's blog mainly focuses on acticles on Android Development and Tech.

url: 'https://sharkaboi.github.io'
